const id = { name:'id',in:'path',required:true,schema:{type:'string'},description:'Visible Blueprint UUID or portable key' };
const n = { name:'n',in:'path',required:true,schema:{type:'integer',minimum:1} };
const errors = { '403':{description:'Required scope or plan authority missing; response names the scope'},'404':{description:'Absent and unreadable resources share one concealed response'},'409':{description:'Version state, archived target, key reuse, or publication conflict'},'422':{description:'Document, value, binding, reference, or size validation refused; no submitted credential is echoed'},'503':{description:'Operation unavailable; retry an uncertain instantiation using the SAME idempotency key'} };
const documentSchema = { type:'object',additionalProperties:false,required:['schemaVersion','blueprint','parameters','references','target','phases','tasks','humanGates','reports','dependencies'],properties:{
  schemaVersion:{type:'string',enum:['rh.blueprint/1.0']},blueprint:{type:'object'},parameters:{type:'array',maxItems:50,items:{type:'object'}},references:{type:'array',maxItems:100,items:{type:'object'}},target:{type:'object'},phases:{type:'array',maxItems:20,items:{type:'object'}},tasks:{type:'array',maxItems:100,items:{type:'object'}},humanGates:{type:'array',maxItems:20,items:{type:'object'}},reports:{type:'array',maxItems:20,items:{type:'object'}},dependencies:{type:'array',maxItems:500,items:{type:'object'}} },description:'Portable rh.blueprint/1.0 data. All nested objects are closed and validated server-side. No installed IDs, addresses, credential literals, executable logic, arming or authority objects. Canonical size is min(65536, active JSON body limit minus4096) UTF-8 bytes.' };
const request = (schema: unknown) => ({required:true,content:{'application/json':{schema}}});
const input = {type:'object',additionalProperties:false,required:['target','parameterValues'],properties:{target:{type:'object',additionalProperties:false,required:['mode'],properties:{mode:{type:'string',enum:['new-project','existing-project']},project:{type:'string',description:'Required only for existing-project and must resolve to the Project selected by the document project-ref parameter'}}},parameterValues:{type:'object',description:'Declared typed answers only; defaults materialized server-side and credential-shaped values refused before hashing'}}};
const operation = (summary: string, parameters: unknown[] = [], requestBody?: unknown, created=false) => ({summary,tags:['Blueprints'],parameters,...(requestBody ? {requestBody}:{}),responses:{[created?'201':'200']:{description:'Successful result in the standard success envelope'},...errors}});
const uuid = {type:'string',pattern:'^[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$'};
const revision = {type:'string',pattern:'^[0-9a-f]{32}$'};
const confirmationHash = {type:'string',pattern:'^[0-9a-f]{64}$'};
const confirmedTasks = {type:'array',minItems:1,maxItems:100,items:{type:'object',additionalProperties:false,required:['id','revision'],properties:{id:uuid,revision}}};
const setupErrors = {'403':{description:'BLUEPRINT_AUTHORITY_REQUIRED or typed canonical assignment refusal; caller needs blueprints:use, tasks:write and services:invoke plus live assignment authority'},'404':{description:'BLUEPRINT_SETUP_NOT_FOUND conceals private, absent or invisible setup'},'409':{description:'BLUEPRINT_SETUP_CHANGED for a stale exact set/version/hash, or IDEMPOTENCY_KEY_REUSED for changed content; do not refresh preview during an uncertain retry'},'422':{description:'BLUEPRINT_SETUP_INPUT_INVALID; closed exact confirmation body required'},'503':{description:'Retry the identical confirmed body and retained Idempotency-Key after an uncertain outcome'}};
const newWarrant={type:'object',additionalProperties:false,required:['holderPrincipalId','ceilingProfileId','expiresAt'],properties:{holderPrincipalId:uuid,ceilingProfileId:uuid,expiresAt:{type:'string',format:'date-time'}}};
const setupChoice={oneOf:[{required:['warrantId']},{required:['createWarrant']}],properties:{warrantId:uuid,createWarrant:newWarrant}};
const setupPathId = {...id,schema:uuid,description:'Created instantiation UUID; staged setup is private to its actor or a root login session'};
export const blueprintPaths: Record<string,any> = {
  '/blueprints':{
    get:operation('Discover published Blueprints under blueprints:read OR independently granted blueprints:use; use-only projection contains interview fields and no history or ledger'),
    post:operation('Create a Blueprint draft (blueprints:write)',[],request(documentSchema),true),
  },
  '/blueprints/capture':{post:operation('Capture a complete readable Phase as draft v1; blueprints:write plus Phase, Project and every Task read',[],request({type:'object',additionalProperties:false,required:['phaseId'],properties:{phaseId:uuid,projectId:uuid,name:{type:'string'},key:{type:'string'}}}),true)},
  '/blueprints/import':{post:operation('Import as draft only; explicit rename resolves key collision; never publishes',[],request({type:'object',additionalProperties:false,required:['document'],properties:{document:documentSchema,rename:{type:'string'}}}),true)},
  '/blueprints/{id}':{get:operation('Describe a visible Blueprint; use-only callers receive only its current published version',[id,{name:'version',in:'query',schema:{type:'integer',minimum:1}}])},
  '/blueprints/{id}/versions':{get:operation('Version history under blueprints:read; draft/review visibility additionally requires object write',[id]),post:operation('Add the next monotonic draft version (blueprints:write)',[id],request(documentSchema),true)},
  '/blueprints/{id}/versions/{n}':{patch:operation('Replace editable draft content; submitted versions are immutable',[id,n],request(documentSchema))},
  '/blueprints/{id}/versions/{n}/export':{get:{...operation('Export previously published portable JSON after revalidation (blueprints:read)',[id,n]),responses:{'200':{description:'Canonical JSON attachment',content:{'application/json':{schema:documentSchema}}},...errors}}},
  '/blueprints/{id}/instantiations/preview':{post:operation('Zero-write preview under blueprints:use and target visibility only; computes and REPORTS whole-plan authority and structured access refusals for every unavailable reference',[id],request(input))},
  '/blueprints/{id}/instantiations':{
    get:operation('List caller-visible ledger rows (blueprints:read); raw answers only for original caller or root login session',[id]),
    post:{...operation('Instantiate through canonical writers in caller identity in one transaction. All Tasks remain PARKED. Same key/equivalent request returns original snapshot/status even after retirement; archive and concealment gates still apply. Never retry an uncertain result with a new key.',[id,{name:'Idempotency-Key',in:'header',required:true,schema:{type:'string',minLength:16,maxLength:128}}],request(input),true),responses:{'201':{description:'Original creation or exact committed replay; created Project/Phase/Task/Report IDs, instantiationId and warnings'},'400':{description:'IDEMPOTENCY_KEY_REQUIRED before database connection'},...errors}},
  },
  '/instantiations/{id}':{get:operation('Read a ledger row through Blueprint and root Project visibility; redacted parameter projection for other readers',[{...id,description:'Instantiation UUID'}])},
  '/instantiations/{id}/setup/preview':{post:{...operation('Preview separate setup using an existing Warrant or a human-session proposal for a new Warrant. Shows exact Task versions, profiles and grants. Writes nothing.',[setupPathId],request({type:'object',additionalProperties:false,...setupChoice})),responses:{'200':{description:'Complete private literal setup plan; no authority is conveyed by the document',content:{'application/json':{schema:{type:'object',additionalProperties:false,required:['success','plan'],properties:{success:{const:true},plan:{type:'object',additionalProperties:false,required:['instantiationId','projectId','tasks','allParked','assignmentOnly','confirmationHash'],properties:{instantiationId:uuid,projectId:uuid,warrantId:uuid,createWarrant:{type:'object'},grants:{type:'array',items:{type:'object'}},requiresStepUp:{type:'boolean'},allParked:{const:true},assignmentOnly:{type:'boolean'},confirmationHash,tasks:{type:'array',items:{type:'object',additionalProperties:false,required:['id','revision','title','phaseId','executionProfile'],properties:{id:uuid,revision,title:{type:'string'},phaseId:{oneOf:[uuid,{type:'null'}]},executionProfile:{type:'object',description:'Resolved canonical execution profile displayed literally; not accepted in the confirmation body'}}}}}}}}}}},...setupErrors}}},
  '/instantiations/{id}/setup':{post:{...operation('Explicitly confirm the displayed exact setup. Canonical assignment is transactional; all Tasks stay parked. New Warrant creation requires a human login session and a warrant.create step-up token. No implicit setup after instantiate or future Task enrollment.',[setupPathId,{name:'Idempotency-Key',in:'header',required:true,schema:{type:'string',minLength:16,maxLength:128}}],request({type:'object',additionalProperties:false,required:['tasks','confirmationHash'],oneOf:setupChoice.oneOf,properties:{...setupChoice.properties,stepUpToken:{type:'string'},tasks:confirmedTasks,confirmationHash}})),responses:{'200':{description:'Original or replayed safe assignment receipt; never profiles, options or parameters',content:{'application/json':{schema:{type:'object',additionalProperties:false,required:['success','status','instantiationId','taskIds','warrantId','assigned','armed'],properties:{success:{const:true},status:{const:200},instantiationId:uuid,taskIds:{type:'array',items:uuid},warrantId:uuid,assigned:{const:true},armed:{const:false}}}}}},'400':{description:'IDEMPOTENCY_KEY_REQUIRED'},...setupErrors}}},
};
for (const [action,description] of Object.entries({submit:'draft to review, freezing content (blueprints:write)',withdraw:'review to draft, author only (blueprints:write)',reject:'review to draft with required note (blueprints:admin)',publish:'review to published, never self-publish and never Agent; atomically supersedes previous published version (blueprints:admin)',retire:'published to retired, stops fresh instantiation and leaves instances untouched; never Agent (blueprints:admin)'})) {
  blueprintPaths[`/blueprints/{id}/versions/{n}/${action}`]={post:operation(description,[id,n],request({type:'object',additionalProperties:false,...(action==='reject'?{required:['note']}:{}),properties:{note:{type:'string',maxLength:2000,...(action==='reject'?{minLength:1}:{})}}}))};
}
